// This file is auto-generated by Tuono

import { createRoute, __tuono__internal__lazyLoadRoute } from 'tuono'

import RootLayoutImport from './routes/__layout'

const IndexImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/index'),
)
const PostscatchallImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/[...catch_all]'),
)

const rootRoute = createRoute({ isRoot: true, component: RootLayoutImport })

const Index = createRoute({ component: IndexImport })
const Postscatchall = createRoute({ component: PostscatchallImport })

// Create/Update Routes

const IndexRoute = Index.update({
  path: '/',
  getParentRoute: () => rootRoute,
})

const PostscatchallRoute = Postscatchall.update({
  path: '/posts/[...catch_all]',
  getParentRoute: () => rootRoute,
  hasHandler: true,
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([IndexRoute, PostscatchallRoute])
