// This file is auto-generated by Tuono

import { createRoute, __tuono__internal__lazyLoadRoute } from 'tuono'

import RootLayoutImport from './routes/__layout'

const AboutImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/about'),
)
const IndexImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/index'),
)
const PostsMyPostImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/my-post'),
)

const rootRoute = createRoute({ isRoot: true, component: RootLayoutImport })

const About = createRoute({ component: AboutImport })
const Index = createRoute({ component: IndexImport })
const PostsMyPost = createRoute({ component: PostsMyPostImport })

// Create/Update Routes

const AboutRoute = About.update({
  path: '/about',
  getParentRoute: () => rootRoute,
})

const IndexRoute = Index.update({
  path: '/',
  getParentRoute: () => rootRoute,
})

const PostsMyPostRoute = PostsMyPost.update({
  path: '/posts/my-post',
  getParentRoute: () => rootRoute,
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  PostsMyPostRoute,
])
