// File automatically generated by tuono
// Do not manually update this file
import 'vite/modulepreload-polyfill'
import { hydrate } from 'tuono/hydration'

// Import the generated route tree
import { routeTree } from './routeTree.gen'

hydrate(routeTree)
