// File automatically generated by tuono
// Do not manually update this file
import { serverSideRendering } from 'tuono/ssr'

import { routeTree } from './routeTree.gen'

export const renderFn = serverSideRendering(routeTree)
