name: Check jobs result
description: Check that a given string of job results join doesn't contain 'failed' or 'cancelled'

inputs:
  results:
    description: "string containing a list of results. E.g.: `join(needs.*.result, ',')`"
    required: true

runs:
  using: composite
  env:
    FAILURE: ${{ contains(inputs.results, 'failure') }}
    CANCELLED: ${{ contains(inputs.results, 'cancelled') }}
  steps:
    - name: Check for failure or cancelled jobs result
      shell: bash
      run: |
        echo "Failure: $FAILURE - Cancelled: $CANCELLED"
        if [ "$FAILURE" = "false" ] && [ "$CANCELLED" = "false" ]; then
          exit 0
        else
          exit 1
        fi
