name: Documentation Website CI

on:
  push:
    branches:
      - 'main'
    # match
    # - all files inside `apps/documentation` and `.github`
    # - all files in the root expect `Cargo.toml`
    paths:
      - '.github/**'
      - '*'
      - '!Cargo.toml'
      - 'apps/documentation/**'
  pull_request:
    # same as `on.push.paths`
    paths:
      - '.github/**'
      - '*'
      - '!Cargo.toml'
      - 'apps/documentation/**'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Check build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        uses: ./.github/actions/install-node-dependencies

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      # ⬇️ Keep in sync with `.github/workflows/deploy-documentation.yml`
      - name: Read tuono version used by the documentation
        id: get_tuono_version
        run: |
          VERSION=$(pnpm ls tuono --filter=documentation | grep "tuono " | sed -E 's/.* ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install tuono
        run: cargo install tuono@${{ steps.get_tuono_version.outputs.version }}
      # ⬆️

      - name: Build project
        working-directory: ./apps/documentation
        run: tuono build --static

  code_check:
    name: Check format, lint and types
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        uses: ./.github/actions/install-node-dependencies

      - name: Check formatting
        run: pnpm docs:format:check

      - name: Lint
        run: pnpm docs:lint

      - name: Types
        run: pnpm docs:types
