name: Repo root CI

# All workflows are triggered based on specific paths,
# the root repository is something that is not applicable to rust nor typescript
# so it has been moved in a standalone workflow

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        uses: ./.github/actions/install-node-dependencies

      - name: Test project
        run: pnpm repo:root:format:check

  ci_ok:
    name: OK
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: always()
    needs: [format]
    steps:
      - name: Check jobs result
        uses: ./.github/actions/check-jobs-result
        with:
          results: ${{ join(needs.*.result, ',') }}
